#!/bin/bash

# Enable debugging mode
set -x

cat /etc/ui_use_flags.txt

prefix=/usr/local

wget https://github.com/musamaanjum/public/raw/refs/heads/main/hardware_probe -O $prefix/hardware_probe
ls -al $prefix | grep hardware_probe
chmod +x $prefix/hardware_probe
file $prefix/hardware_probe
$prefix/hardware_probe

rm $prefix/hardware_probe
